// Criminal Intelligence Bureau (CIB) — the fixed 52-incident archive.
//
// This is a deliberately hand-authored dataset (not generated at runtime)
// covering July 2024 through August 2026. cib-data.spec.ts validates the
// archive window and its deliberate aggregate distribution.

import { CibIncident, CibIncidentCopy } from './cib.model';

export const CIB_ARCHIVE_MONTHS: readonly string[] = [
  '2024-07',
  '2024-08',
  '2024-09',
  '2024-10',
  '2024-11',
  '2024-12',
  '2025-01',
  '2025-02',
  '2025-03',
  '2025-04',
  '2025-05',
  '2025-06',
  '2025-07',
  '2025-08',
  '2025-09',
  '2025-10',
  '2025-11',
  '2025-12',
  '2026-01',
  '2026-02',
  '2026-03',
  '2026-04',
  '2026-05',
  '2026-06',
  '2026-07',
  '2026-08',
];

export const CIB_INCIDENTS: readonly CibIncident[] = [
  {
    id: 'CIB-001',
    date: '2024-07-05',
    hour: 7,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'closed',
  },
  {
    id: 'CIB-002',
    date: '2024-08-27',
    hour: 14,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'property-damage',
    status: 'open',
    image: 'assets/images/couch-armrest-detail.jpg',
  },
  {
    id: 'CIB-003',
    date: '2024-08-05',
    hour: 18,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'public-disturbance',
    status: 'closed',
  },
  {
    id: 'CIB-004',
    date: '2024-08-19',
    hour: 9,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'obstruction',
    status: 'open',
    image: 'assets/images/blog-shop-entry.jpg',
  },
  {
    id: 'CIB-005',
    date: '2024-09-05',
    hour: 19,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'open',
    image: 'assets/images/theft-bread.jpg',
    storyRoute: '/theft-and-destruction',
  },
  {
    id: 'CIB-006',
    date: '2024-12-27',
    hour: 11,
    suspectIds: ['sawito'],
    duoRelationship: 'not-applicable',
    offenceId: 'property-damage',
    status: 'closed',
    image: 'assets/images/sawito-dog-selfie.jpg',
  },
  {
    id: 'CIB-007',
    date: '2024-10-05',
    hour: 17,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'public-disturbance',
    status: 'open',
    image: 'assets/images/jury-verdict-awaited.jpg',
    storyRoute: '/jury-tampering',
  },
  {
    id: 'CIB-008',
    date: '2024-10-19',
    hour: 10,
    suspectIds: ['sawito'],
    duoRelationship: 'not-applicable',
    offenceId: 'obstruction',
    status: 'closed',
  },
  {
    id: 'CIB-009',
    date: '2024-11-05',
    hour: 8,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'open',
  },
  {
    id: 'CIB-010',
    date: '2025-02-12',
    hour: 15,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'property-damage',
    status: 'open',
  },
  {
    id: 'CIB-011',
    date: '2024-12-05',
    hour: 20,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'public-disturbance',
    status: 'closed',
  },
  {
    id: 'CIB-012',
    date: '2024-12-19',
    hour: 9,
    suspectIds: ['sawito'],
    duoRelationship: 'not-applicable',
    offenceId: 'obstruction',
    status: 'open',
  },
  {
    id: 'CIB-013',
    date: '2025-01-05',
    hour: 12,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'closed',
  },
  {
    id: 'CIB-014',
    date: '2025-01-19',
    hour: 16,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'property-damage',
    status: 'open',
    image: 'assets/images/theft-shoe.jpg',
    storyRoute: '/theft-and-destruction',
  },
  {
    id: 'CIB-015',
    date: '2025-02-05',
    hour: 18,
    suspectIds: ['pikette'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'open',
    image: 'assets/images/pikette-windowsill.jpg',
  },
  {
    id: 'CIB-016',
    date: '2025-02-19',
    hour: 11,
    suspectIds: ['le-criminel', 'pikette'],
    duoRelationship: 'allied',
    offenceId: 'property-damage',
    status: 'open',
    image: 'assets/images/pikette-dog-couch.jpg',
  },
  {
    id: 'CIB-017',
    date: '2025-03-05',
    hour: 7,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'open',
  },
  {
    id: 'CIB-018',
    date: '2025-02-27',
    hour: 14,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'property-damage',
    status: 'closed',
    image: 'assets/images/couch-crime-scene.jpg',
    storyRoute: '/couch',
  },
  {
    id: 'CIB-019',
    date: '2025-04-05',
    hour: 19,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'public-disturbance',
    status: 'open',
  },
  {
    id: 'CIB-020',
    date: '2025-04-19',
    hour: 10,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'closed',
  },
  {
    id: 'CIB-021',
    date: '2025-05-05',
    hour: 8,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'closed',
    image: 'assets/images/blog-cafe-standoff.jpg',
  },
  {
    id: 'CIB-022',
    date: '2025-06-27',
    hour: 15,
    suspectIds: ['sawito'],
    duoRelationship: 'not-applicable',
    offenceId: 'property-damage',
    status: 'open',
    image: 'assets/images/blog-cheek-to-cheek.jpg',
  },
  {
    id: 'CIB-023',
    date: '2025-06-05',
    hour: 17,
    suspectIds: ['le-criminel', 'pikette'],
    duoRelationship: 'rivals',
    offenceId: 'public-disturbance',
    status: 'closed',
    image: 'assets/images/pikette-dog-couch.jpg',
  },
  {
    id: 'CIB-024',
    date: '2025-06-19',
    hour: 9,
    suspectIds: ['le-criminel', 'pikette'],
    duoRelationship: 'allied',
    offenceId: 'obstruction',
    status: 'open',
  },
  {
    id: 'CIB-025',
    date: '2025-07-05',
    hour: 20,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'open',
  },
  {
    id: 'CIB-026',
    date: '2025-07-19',
    hour: 14,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'property-damage',
    status: 'open',
  },
  {
    id: 'CIB-027',
    date: '2025-08-05',
    hour: 18,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'public-disturbance',
    status: 'open',
  },
  {
    id: 'CIB-028',
    date: '2025-09-27',
    hour: 11,
    suspectIds: ['sawito'],
    duoRelationship: 'not-applicable',
    offenceId: 'obstruction',
    status: 'open',
  },
  {
    id: 'CIB-029',
    date: '2025-09-05',
    hour: 7,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'open',
  },
  {
    id: 'CIB-030',
    date: '2025-09-19',
    hour: 16,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'property-damage',
    status: 'closed',
  },
  {
    id: 'CIB-031',
    date: '2025-10-05',
    hour: 19,
    suspectIds: ['le-criminel', 'pikette'],
    duoRelationship: 'rivals',
    offenceId: 'public-disturbance',
    status: 'open',
  },
  {
    id: 'CIB-032',
    date: '2025-10-19',
    hour: 10,
    suspectIds: ['pikette'],
    duoRelationship: 'not-applicable',
    offenceId: 'obstruction',
    status: 'closed',
    image: 'assets/images/pikette-couch-visit.jpg',
  },
  {
    id: 'CIB-033',
    date: '2025-11-05',
    hour: 12,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'closed',
  },
  {
    id: 'CIB-034',
    date: '2025-10-27',
    hour: 15,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'property-damage',
    status: 'open',
    image: 'assets/images/blog-full-capacity.jpg',
  },
  {
    id: 'CIB-035',
    date: '2025-12-05',
    hour: 17,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'closed',
  },
  {
    id: 'CIB-036',
    date: '2025-12-19',
    hour: 9,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'obstruction',
    status: 'open',
    image: 'assets/images/dog-floor-portrait.jpg',
  },
  {
    id: 'CIB-037',
    date: '2026-01-05',
    hour: 8,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'open',
    image: 'assets/images/theft-bread.jpg',
  },
  {
    id: 'CIB-038',
    date: '2026-02-12',
    hour: 14,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'property-damage',
    status: 'open',
    image: 'assets/images/blog-blanket-hoard.jpg',
  },
  {
    id: 'CIB-039',
    date: '2026-02-05',
    hour: 20,
    suspectIds: ['le-criminel', 'pikette'],
    duoRelationship: 'rivals',
    offenceId: 'public-disturbance',
    status: 'open',
    image: 'assets/images/couch-dog-caught.jpg',
  },
  {
    id: 'CIB-040',
    date: '2026-02-19',
    hour: 11,
    suspectIds: ['le-criminel', 'pikette'],
    duoRelationship: 'allied',
    offenceId: 'obstruction',
    status: 'open',
    image: 'assets/images/pikette-dog-couch.jpg',
  },
  {
    id: 'CIB-041',
    date: '2026-03-05',
    hour: 7,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'closed',
    image: 'assets/images/blog-waffle-watch.jpg',
  },
  {
    id: 'CIB-042',
    date: '2026-02-27',
    hour: 16,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'property-damage',
    status: 'closed',
  },
  {
    id: 'CIB-043',
    date: '2026-04-05',
    hour: 18,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'public-disturbance',
    status: 'open',
    image: 'assets/images/blog-mailman-standoff.jpg',
  },
  {
    id: 'CIB-044',
    date: '2026-04-19',
    hour: 10,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'closed',
    image: 'assets/images/blog-bed-nap.jpg',
  },
  {
    id: 'CIB-045',
    date: '2026-05-05',
    hour: 13,
    suspectIds: ['sawito'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'open',
  },
  {
    id: 'CIB-046',
    date: '2026-06-27',
    hour: 15,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'property-damage',
    status: 'open',
    image: 'assets/images/blog-garden-wall.jpg',
  },
  {
    id: 'CIB-047',
    date: '2026-06-05',
    hour: 19,
    suspectIds: ['le-criminel', 'pikette'],
    duoRelationship: 'truce',
    offenceId: 'public-disturbance',
    status: 'closed',
  },
  {
    id: 'CIB-048',
    date: '2026-06-19',
    hour: 9,
    suspectIds: ['le-criminel', 'pikette'],
    duoRelationship: 'allied',
    offenceId: 'obstruction',
    status: 'open',
  },
  {
    id: 'CIB-049',
    date: '2026-07-05',
    hour: 13,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'closed',
    image: 'assets/images/cib-aug-food-surveillance.jpg',
  },
  {
    id: 'CIB-050',
    date: '2026-08-27',
    hour: 16,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'property-damage',
    status: 'open',
    image: 'assets/images/cib-aug-shoe-inspection.jpg',
  },
  {
    id: 'CIB-051',
    date: '2026-08-05',
    hour: 18,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'public-disturbance',
    status: 'open',
    image: 'assets/images/cib-aug-balcony-grate.jpg',
    storyRoute: '/pigeon',
  },
  {
    id: 'CIB-052',
    date: '2026-08-19',
    hour: 9,
    suspectIds: ['le-criminel'],
    duoRelationship: 'not-applicable',
    offenceId: 'snack-theft',
    status: 'closed',
    image: 'assets/images/cib-aug-croissant-watch.jpg',
  },
];

// English incident copy, keyed by incident ID. Full CibContent/i18n wiring
// is Task 4's job; this is the minimal English-only slice Task 2 needs.
export const CIB_INCIDENT_COPY_EN: Readonly<Record<string, CibIncidentCopy>> = {
  'CIB-001': {
    title: "Restaurant staff compromised by calculated charm",
    summary: "Le Criminel worked the terrace table by table until restaurant staff surrendered extra croissant.",
    imageAlt: "",
  },
  'CIB-002': {
    title: 'Couch seam subjected to sustained investigation',
    summary:
      'Le Criminel returned repeatedly to one loose seam until the stuffing became accessible. Supervision stopped the inspection before the entire cushion was opened.',
    imageAlt: 'Torn stitching and exposed stuffing on a couch cushion seam.',
  },
  'CIB-003': {
    title: 'Friendly neighbour identified as permanent enemy',
    summary:
      'The elderly neighbour greeted Le Criminel kindly in the communal hall. Le Criminel answered with the same personal hostility he reserves for every encounter with this entirely innocent man.',
    imageAlt: '',
  },
  'CIB-004': {
    title: 'Apartment hallway occupied during departure',
    summary:
      'Le Criminel planted himself between the apartment door and the lift while deciding whether the outing was acceptable. Everyone else waited for the ruling.',
    imageAlt: 'Le Criminel on a leash just inside a tiled entryway.',
  },
  'CIB-005': {
    title: 'Bread transferred into protective custody',
    summary: 'The accused declined to identify the original owner. Crumbs contradicted the statement.',
    imageAlt: 'Half a loaf of bread on the kitchen floor, one end visibly gnawed.',
  },
  'CIB-006': {
    title: 'Phone case cracked during ill-advised photo op',
    summary:
      "Sawito, attempting a selfie with the dog mid-leap, dropped the phone on the one tile floor in the house. The photo, for the record, came out fine.",
    imageAlt: 'Sawito mid-selfie with the dog leaping toward the camera.',
  },
  'CIB-007': {
    title: 'Extended-family gathering disrupted by unsolicited opinion',
    summary:
      'Subject inserted himself into a conversation he was not party to, barking at a volume calibrated to end it. It ended it.',
    imageAlt: 'Le Criminel sitting solemnly, awaiting judgment.',
  },
  'CIB-008': {
    title: 'Doorway blocked mid-delivery, on purpose',
    summary:
      'Sawito stood directly in the courier’s path while deciding, at length, whether a signature was required. It was not. He stood there anyway.',
    imageAlt: '',
  },
  'CIB-009': {
    title: 'Breakfast toast removed during a brief distraction',
    summary:
      'A turned back created an opening of less than three seconds. Le Criminel used it to remove toast from the edge of the table and retreat beneath the chair.',
    imageAlt: '',
  },
  'CIB-010': {
    title: 'Second shoe entered active play',
    summary:
      'Le Criminel selected a recently removed shoe, carried it to the living room, and worked the laces until intervention became unavoidable.',
    imageAlt: '',
  },
  'CIB-011': {
    title: 'Neighbour detected through a closed apartment door',
    summary:
      'Footsteps in the shared corridor were correctly identified as the nice elderly neighbour. Le Criminel began the usual protest before the man had reached the landing.',
    imageAlt: '',
  },
  'CIB-012': {
    title: "Holiday preparations delayed by handler indecision",
    summary: "Sawito reconsidered one decoration long enough to block the apartment hallway for everyone else.",
    imageAlt: "",
  },
  'CIB-013': {
    title: 'Parmesan block removed in its entirety',
    summary:
      'While the owner was in the shower, Le Criminel stole an entire block of parmesan and ate it on the bed. Crumbs and oil marks established the location beyond dispute.',
    imageAlt: '',
  },
  'CIB-014': {
    title: "Worn shoe subjected to another inspection",
    summary: "Le Criminel carried the shoe away and worked the laces until intervention became unavoidable.",
    imageAlt: "A single sneaker lying in the grass with visible damage.",
  },
  'CIB-015': {
    title: "First Pikette sighting includes immediate food inspection",
    summary: "Pikette arrived for her first recorded visit, checked the food bowls, and treated everything within reach as shared property.",
    imageAlt: "Pikette sitting on the apartment windowsill beside the food bowls.",
  },
  'CIB-016': {
    title: "First meeting establishes immediate mutual hostility",
    summary: "Le Criminel and Pikette exchanged warnings and spent the rest of the visit monitoring each other from opposite ends of the couch.",
    imageAlt: "Pikette and Le Criminel sharing the couch while watching each other.",
  },
  'CIB-017': {
    title: 'Dropped sausage intercepted before recovery',
    summary:
      'A sausage reached the floor and Le Criminel reached it first. The evidence was swallowed before any meaningful recovery effort could begin.',
    imageAlt: '',
  },
  'CIB-018': {
    title: 'Shoe operation spreads to the couch',
    summary:
      'Le Criminel carried a captured shoe onto the couch and used the armrest for leverage. The shoe, upholstery, and household patience all sustained damage.',
    imageAlt: 'Claw marks visible on a couch armrest, close up.',
  },
  'CIB-019': {
    title: 'Neighbour crossing monitored from the couch',
    summary:
      'Le Criminel spotted the elderly neighbour from the apartment window and followed his progress across the courtyard with sustained disapproval.',
    imageAlt: '',
  },
  'CIB-020': {
    title: 'Kitchen access demanded during food preparation',
    summary:
      'Le Criminel occupied the narrow kitchen entrance and monitored every movement between the counter and table. Repeated removal attempts produced immediate returns.',
    imageAlt: '',
  },
  'CIB-021': {
    title: "Lunch placed under continuous surveillance",
    summary: "Le Criminel tracked the plate from arrival to the final bite. Every fork movement produced a fresh request for transfer.",
    imageAlt: "Le Criminel watching food closely from beside an outdoor cafe table.",
  },
  'CIB-022': {
    title: 'Reading glasses sat on and structurally compromised',
    summary:
      "Sawito's glasses, left on the arm of the chair for 'just a second,' were located under the same chair, one lens detached. He blames the chair.",
    imageAlt: 'Sawito, wearing his glasses, cheek to cheek with the dog.',
  },
  'CIB-023': {
    title: "Pikette returns and hostilities resume immediately",
    summary: "The second recorded visit began where the first ended: both animals claimed the same couch territory and rejected the other occupant.",
    imageAlt: "Pikette and Le Criminel occupying the couch during a visit.",
  },
  'CIB-024': {
    title: "Couch passage closed during a two-animal standoff",
    summary: "Pikette held one end of the couch while Le Criminel held the other until food in the kitchen ended the dispute.",
    imageAlt: "",
  },
  'CIB-025': {
    title: 'Croissant crumbs acquired from a compromised witness',
    summary:
      'Restaurant staff again interpreted prolonged staring as hunger and supplied croissant fragments. Le Criminel accepted the transfer without correcting the misunderstanding.',
    imageAlt: '',
  },
  'CIB-026': {
    title: 'Food bag searched immediately after delivery',
    summary:
      'Le Criminel inserted his head into the shopping bag before it had been fully unpacked. Vegetables were approved; all other contents remained targets.',
    imageAlt: '',
  },
  'CIB-027': {
    title: 'Post-dinner gas event clears living room',
    summary:
      'A meal served without sufficient vegetables was followed by an atmospheric incident severe enough to empty the immediate seating area. Classification upgraded to terror weapon.',
    imageAlt: '',
  },
  'CIB-028': {
    title: "Departure delayed by a missing set of keys",
    summary: "Sawito searched every visible surface before finding the keys in the pocket he had already checked.",
    imageAlt: "",
  },
  'CIB-029': {
    title: 'Vegetable allocation prevents escalation',
    summary:
      'Dinner included an acceptable vegetable component. Le Criminel ate without protest and the household recorded no subsequent gas emergency.',
    imageAlt: '',
  },
  'CIB-030': {
    title: 'Shoe lace shortened during unsupervised access',
    summary:
      'Le Criminel was left alone with a shoe long enough to pull out the lace and chew through one end. The shoe remains wearable in a strictly technical sense.',
    imageAlt: '',
  },
  'CIB-031': {
    title: "Third Pikette visit resumes the established feud",
    summary: "Pikette returned and Le Criminel treated the arrival as a renewal of unfinished business.",
    imageAlt: "",
  },
  'CIB-032': {
    title: "Preferred couch cushion claimed for the visit",
    summary: "Pikette selected the center cushion and remained there despite attempts to restore the normal seating arrangement.",
    imageAlt: "Pikette occupying the center couch cushion during a visit.",
  },
  'CIB-033': {
    title: 'Parmesan packaging triggers repeat-offender response',
    summary:
      'Opening a new block of parmesan brought Le Criminel into the kitchen at speed. The cheese remained secured and was never left within shower-time reach.',
    imageAlt: '',
  },
  'CIB-034': {
    title: "Shoe lining removed inside the apartment",
    summary: "Le Criminel carried a shoe from the entrance into the living room and pulled out enough lining to make the damage obvious.",
    imageAlt: "Le Criminel standing on a leash during an outdoor walk.",
  },
  'CIB-035': {
    title: 'Cafe staff approached for unauthorized pastry',
    summary:
      'Le Criminel ignored his own handler and concentrated on a member of restaurant staff carrying pastries. The charm offensive produced an additional croissant piece.',
    imageAlt: '',
  },
  'CIB-036': {
    title: 'Doorway occupied in full stretch, blocking both directions',
    summary:
      'Subject selected the exact center of the doorway for a nap, achieving maximum surface coverage. Traffic rerouted around him for two hours.',
    imageAlt: 'Le Criminel lying stretched across a hallway floor.',
  },
  'CIB-037': {
    title: 'Second loaf lost under nearly identical circumstances',
    summary:
      'This is not the first bread-related incident on file, nor, investigators suspect, will it be the last. The technique has clearly been refined.',
    imageAlt: 'A second loaf of bread on the floor, similarly gnawed.',
  },
  'CIB-038': {
    title: 'Parmesan residue discovered in bedding',
    summary:
      'A follow-up inspection of the bed found cheese crumbs worked into the blanket. The evidence is consistent with the earlier whole-block parmesan theft.',
    imageAlt: 'Le Criminel curled up asleep beneath a heavy blanket on the couch.',
  },
  'CIB-039': {
    title: "Close-range Pikette photograph triggers renewed protest",
    summary: "Pikette remained still for a surveillance photograph while Le Criminel objected from the other side of the room.",
    imageAlt: "Le Criminel looking up sharply from the rug during the visit.",
  },
  'CIB-040': {
    title: "Temporary window alliance observed during February visit",
    summary: "Both animals paused hostilities to watch movement outside from the couch. Cooperation ended when the window became quiet.",
    imageAlt: "Pikette and Le Criminel sharing the couch during a temporary alliance.",
  },
  'CIB-041': {
    title: 'Breakfast subjected to close-range acquisition attempt',
    summary:
      'Le Criminel maintained position beside the breakfast table and tracked every movement of the pastry. The croissant remained intact only through continuous supervision.',
    imageAlt: 'Le Criminel staring fixedly at a waffle left on an outdoor table.',
  },
  'CIB-042': {
    title: 'Shoe storage breached after lights out',
    summary:
      'A shoe removed before bed was recovered from the living room with wet laces and fresh tooth marks. Le Criminel was asleep beside it when questioned.',
    imageAlt: '',
  },
  'CIB-043': {
    title: 'Neighbour receives another hostile reception',
    summary:
      'The elderly neighbour offered a calm greeting in the communal entrance. Le Criminel responded as though a long-running personal feud had just been renewed.',
    imageAlt: 'Le Criminel sitting alert on a leash near the street.',
  },
  'CIB-044': {
    title: 'Dinner carried onto the bed for unauthorized inspection',
    summary:
      'Le Criminel followed food into the bedroom and attempted to inspect the plate at mattress height. Access was denied before the parmesan precedent could repeat.',
    imageAlt: 'Le Criminel sprawled on his back across a bed, taking up the whole width.',
  },
  'CIB-045': {
    title: 'Last slice claimed under dubious pretense of portion control',
    summary:
      "Sawito took the final slice while explaining, unprompted, that he was 'just evening things out.' No one had asked him to.",
    imageAlt: '',
  },
  'CIB-046': {
    title: "Another shoe removed from the apartment entrance",
    summary: "Le Criminel relocated a shoe to the living room and began working on the heel during an unusually quiet interval.",
    imageAlt: "Le Criminel investigating a stone ledge during an outdoor walk.",
  },
  'CIB-047': {
    title: "Rare quiet couch truce recorded during Pikette visit",
    summary: "Le Criminel and Pikette shared the couch without an argument long enough for the household to document the anomaly.",
    imageAlt: "",
  },
  'CIB-048': {
    title: "Joint couch occupation leaves no useful seat",
    summary: "Pikette and Le Criminel arranged themselves across the available cushions and remained allied against anyone attempting to sit down.",
    imageAlt: "",
  },
  'CIB-049': {
    title: 'Lunch placed under continuous surveillance',
    summary: 'Le Criminel maintained visual contact with the plate from arrival to the final bite. Every fork movement produced a fresh request for transfer.',
    imageAlt: 'Le Criminel watching a plate of pasta from below an outdoor table.',
  },
  'CIB-050': {
    title: 'Shoe inspection resumes while evidence is still being worn',
    summary: 'Le Criminel pressed his face against the shoe, tested the laces, and attempted to begin the usual dismantling process before being interrupted.',
    imageAlt: 'Le Criminel pressing his censored face against a worn shoe at an outdoor table.',
  },
  'CIB-051': {
    title: 'Balcony grate prevents another pigeon pursuit',
    summary: 'Le Criminel locked onto movement beyond the balcony while the large safety grate did exactly what it was installed to do: keep the chase inside the apartment boundary.',
    imageAlt: 'Le Criminel peering over a pizza box beside the full-height balcony safety grate.',
  },
  'CIB-052': {
    title: 'Restaurant staff compromised by calculated charm',
    summary: 'Le Criminel worked the terrace table by table until restaurant staff surrendered extra croissant. The operation relied entirely on eye contact and the appearance of starvation.',
    imageAlt: 'Le Criminel watching a croissant from beside an outdoor cafe table.',
  },
};
